services:
  app:
    build:
      context: .
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}:latest
          - ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    privileged: true
    volumes:
      - .:/app
